### ISSUE TITLE
Errno::ENOENT (No such file or directory @ rb_sysopen - /app/tmp/cache/i18n-js.yml)

### ISSUE THREAD

**Issue by kenips** [PikachuEXE/i18n-js#2]
Hi,

On heroku it's complaining that `Errno::ENOENT (No such file or directory @ rb_sysopen - /app/tmp/cache/i18n-js.yml)` at `vendor/bundle/ruby/2.1.0/gems/i18n-js-pika-3.0.0.rc9/lib/i18n/js/middleware.rb:51:in`initialize'`. Wonder why it's trying to look for that file? I've compiled assets locally.

**Comment by PikachuEXE** [comment]
I guess the middleware should only be injected in development?
I am not sure
I guess I need to ask author

I will try to work on a fix next week

**Comment by kenips** [comment]
No you're right. In the rewrite branch README it's suggested to add `config.middleware.use I18n::JS::Middleware` in `config/application.rb`. It should be updated to `config/environments/development.rb`.

**Comment by kenips** [comment]
By rewrite branch I meant your master branch :)

**Comment by PikachuEXE** [comment]
I am gonna work on the original repo then.
Need to merge back the change!

**Comment by PikachuEXE** [comment]
Close?

**Comment by kenips** [comment]
Oh you got access to original repo? That's awesome!! Close here then.

**Comment by kenips** [comment]
Hey I am so sorry. I didn't read the README at all. It did already say moving to config/development.rb for heroku deployment. So you don't need to make any changes. Perhaps when you have more time make that section a bit more clear. So sorry about that!

**Comment by PikachuEXE** [comment]
I think I would add some inline comment to the code anyway (so difficult to understand it)
