### ISSUE TITLE
config.middleware.use I18n::JS::Middleware issue in rails 4.1.rc2

### ISSUE THREAD

**Issue by xpepermint** [PikachuEXE/i18n-js#3]
I'm not sure if I use this

``` ruby
config.middleware.use I18n::JS::Middleware
```

like I should. It does not create files. I have tu use `rake i18n:js:export`.

**Comment by PikachuEXE** [comment]
Not sure what are you trying to do...
Pre-generate a JS file?

https://github.com/PikachuEXE/i18n-js#rails-app

**Comment by xpepermint** [comment]
I would like the JS files to be generated on each page refresh (in development).

**Comment by PikachuEXE** [comment]
This should work...
What problem do you have in `4.1.0.rc2`?

**Comment by mathiasuhl** [comment]
well the translation file is empty :/ and i have the config.middleware.use I18n::JS::Middleware in place and in the browser the translation file is been loaded but empty

**Comment by PikachuEXE** [comment]
Isn't this already outdated?
If you are talking about 4.1.\* or 4.2.0.beta/rc please open another issue
